# SPDX-License-Identifier: LGPL-2.1-or-later

/**
 * This file is part of libnvme.
 *
 * Copyright (c) 2025, Dell Technologies Inc. or its subsidiaries.
 * Authors: Martin Belanger <Martin.Belanger@dell.com>
 *
 */

LIBNVME_ACCESSORS_3 {
	global:
		libnvme_fabrics_uri_get_scheme;
		libnvme_fabrics_uri_set_scheme;
		libnvme_fabrics_uri_get_port;
		libnvme_fabrics_uri_set_port;
		libnvme_fabrics_uri_get_path_segments;
		libnvme_fabrics_uri_set_path_segments;
};
