.TH "nvme_scan" 9 "nvme_scan" "March 2026" "libnvme API manual" LINUX
.SH NAME
nvme_scan \- Scan NVMe topology
.SH SYNOPSIS
.B "int" nvme_scan
.BI "(const char *config_file "  ","
.BI "struct nvme_global_ctx **ctx "  ");"
.SH ARGUMENTS
.IP "config_file" 12
Configuration file
.IP "ctx" 12
\fInvme_global_ctx\fP object to return
.SH "RETURN"
0 on success or negative error code otherwise
